name: Send Push on New Post

on:
  push:
    paths:
      - "jsons/posts.json"

jobs:
  send-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Firebase Admin
        run: npm install firebase-admin

      - name: Create service account file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json

      - name: Send Push
        run: node sendPush.js
